Bumping gaia.json for 1 gaia-central revision(s) a=gaia-bump
========

https://hg.mozilla.org/integration/gaia-central/rev/649ec3d18952
Author: Anthony Ricaud <anthony@ricaud.me>
Desc: Revert "Merge pull request #14529 from jaoo/933203"

This reverts commit 4dd40d64f137c48104d5f39e48c2ccb0ce9ab78c, reversing
changes made to 0985280ffc917353eb34ff7b0dcc1c152856450c.

This is breaking unit tests:
[system] system/LockScreenConnInfoManager > Single sim devices "before each" hook:
TypeError: MockNavigatorMozIccManager.addIcc is not a function